version: "3.9"
services:
  web:
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal web-server
    network_mode: host
    volumes:
      - "{{config-dir}}:/config"
    restart: unless-stopped

  smtp:
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - "{{config-dir}}:/config"
    restart: unless-stopped

  worker:
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal worker
    network_mode: host
    volumes:
      - "{{config-dir}}:/config"
    restart: unless-stopped

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal
    network_mode: host
    volumes:
      - "{{config-dir}}:/config"
